// var maVariable = true;
// var TypeDeVariable = typeof maVariable;
// alert(TypeDeVariable);
// var humeur=prompt('comment ça va?');
// var prenom =prompt('comment-appelles tu?');
// // alert('humeur');
// // alert('prenom');
// var phrase = 'Tu  t\' appelles ' + prenom  + ' et tu vas ' + humeur + ' !'; 
// alert(phrase);
var varUne, varDeux = 10, varTrois;
var varQuatre;
console.log(varUne) ;
console.log(typeof varUne);
 varUne = "coucou: D";
 console.log(varUne) ;
console.log(typeof varUne);
console.log("Affichage du message de Bienvenue");
 alert('Bienvenue dans notre programme d\'addition');  
var nombreUn =  prompt ('Votre premier nombre ');
console.log("L'utilisateur a entré le nombre;" + nombreUn);
var nombreDeux = prompt ('votre deuxieme nombre');
console.log("L'utilisateur a entré le nombre:" + nombreDeux);
console.log("Oppération en cours");
var Resultat=Number(nombreUn) + Number(nombreDeux);
console.log("Affichage du resultat" + Resultat);
alert(Resultat);
alert( (nombreUn) + (nombreDeux));
alert(typeof nombreUn);
alert(typeof Number(nombreUn));
